version: 2
jobs:

  "node-8.9.0":
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Git Commit Messages
          command: ./node_modules/.bin/commitlint --from=master --to="$CIRCLE_SHA1"
      - run: yarn build
      - run: yarn cover
      - store_test_results:
          path: ~/project/test-results
      - store_artifacts:
          path: ~/project/test-results
      - run: bash <(curl -s https://codecov.io/bash) -s 'test-results/*/coverage'
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "$GIT_EMAIL"
              git config --global user.name "$GIT_NAME"
              echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm run release
            fi

  upgrade:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: sha1sum yarn.lock > yarn.lock.sha1
      - run: yarn upgrade
      - run: "! sha1sum -c yarn.lock.sha1"
      - run: echo "This is where we create a PR";

workflows:
  version: 2
  build:
    jobs:
      - "node-8.9.0"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgrade
