version: 2
jobs:

  git-lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Git Commit Messages
          command: ./node_modules/.bin/commitlint --from=master --to="$CIRCLE_SHA1"

  publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
              - ./node_modules
      - run: yarn build
      - run: yarn cover
      - store_test_results:
          path: ~/project/test-results
      - store_artifacts:
          path: ~/project/test-results
      - run: bash <(curl -s https://codecov.io/bash) -s 'test-results/*/coverage'
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "$GIT_EMAIL"
              git config --global user.name "$GIT_NAME"
              echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm run release || true
            fi

  upgrade:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Automatically upgrade all packages and submit PR with changes.
          shell: /bin/bash
          command: |
            if [ ! `git branch -a | egrep "remotes/origin/automated-package-upgrade"` ]; then
              yarn install --ignore-engines
              sha1sum yarn.lock > yarn.lock.sha1
              yarn upgrade-packages
              sha1sum -c yarn.lock.sha1
              if [ $? -ne 0 ]; then
                git config --global user.email "$GIT_EMAIL"
                git config --global user.name "$GIT_NAME"
                git checkout -b automated-package-upgrade
                git add .
                git commit -m "feat(solution): automated package upgrade"
                git push -u origin automated-package-upgrade
                node ./scripts/pr.js --title "feat(solution): automated package upgrade" --head automated-package-upgrade --base master
              fi
            fi

  node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.0:
    docker:
      - image: circleci/node:9.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.1:
    docker:
      - image: circleci/node:9.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.2:
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.3:
    docker:
      - image: circleci/node:9.3
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.4:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - git-lint
      - node-8:
          requires:
            - git-lint
      - node-9.0:
          requires:
            - git-lint
      - node-9.1:
          requires:
            - git-lint
      - node-9.2:
          requires:
            - git-lint
      - node-9.3:
          requires:
            - git-lint
      - node-9.4:
          requires:
            - git-lint
      - publish:
          requires:
            - git-lint
            - node-8
            - node-9.0
            - node-9.1
            - node-9.2
            - node-9.3
            - node-9.4

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgrade
