version: 2
jobs:

  git-lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Git Commit Messages
          command: ./node_modules/.bin/commitlint --from=master --to="$CIRCLE_SHA1"

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
              - ./node_modules
      - run: yarn build
      - run: yarn cover
      - store_test_results:
          path: ~/project/test-results
      - store_artifacts:
          path: ~/project/test-results
      - run: bash <(curl -s https://codecov.io/bash) -s 'test-results/*/coverage'
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "$GIT_EMAIL"
              git config --global user.name "$GIT_NAME"
              echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm run release || true
            fi

  upgrade:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: "! git branch -a | egrep \"remotes/origin/automated-package-upgrade\""
      - run: yarn install
      - run: sha1sum yarn.lock > yarn.lock.sha1
      - run: yarn upgrade-packages
      - run: "! sha1sum -c yarn.lock.sha1"
      - run: git checkout -b automated-package-upgrade
      - run: git add .
      - run: "git commit -m \"feat(solution): automated package upgrade\""
      - run: git push -u origin automated-package-upgrade
      - run: "node ./scripts/pr.js --title \"feat(solution): automated package upgrade\" --head automated-package-upgrade --base master"

  node-8.9.0:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.0.0:
    docker:
      - image: circleci/node:9.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.1.0:
    docker:
      - image: circleci/node:9.1.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

  node-9.2.0:
    docker:
      - image: circleci/node:9.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - git-lint
      - upgrade
      - node-8.9.0:
          requires:
            - git-lint
      - node-9.0.0:
          requires:
            - git-lint
      - node-9.1.0:
          requires:
            - git-lint
      - node-9.2.0:
          requires:
            - git-lint
      - deploy:
          requires:
            - git-lint
            - node-8.9.0
            - node-9.0.0
            - node-9.1.0
            - node-9.2.0

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgrade
